# Generated by Django 5.2.3 on 2025-07-01 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecocitoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('commune', models.CharField(max_length=100)),
                ('rfid', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('nb_plastique', models.IntegerField(default=0)),
                ('nb_verre', models.IntegerField(default=0)),
                ('nb_metal', models.IntegerField(default=0)),
                ('ecocitoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depot.ecocitoyen')),
            ],
        ),
    ]
