# Generated by Django 5.2 on 2025-07-16 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0001_initial'),
    ]

    operations = [
    ]
