# Generated by Django 5.2 on 2025-08-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0002_fake_add_montant_regle'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='montant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='regle',
            field=models.BooleanField(default=False),
        ),
    ]
